\input texinfo	        @c -*-texinfo-*-
@c %** start of header
@setfilename ebrefile.info
@settitle ebrefile
@c %** end of header

@include ebrefile-ver.texi

@dircategory CD-ROM Book Utilities
@direntry
* ebrefile: (ebrefile).         Refile a catalog file in a CD-ROM book.
@end direntry

@ifinfo
ebrefile: Refile a catalog file in a CD-ROM book, by Motoyuki Kasahara.

Copyright @copyright{} 1998, 99, 2000, 01  Motoyuki Kasahara

Permission is granted to make and distribute verbatim copies of
this manual provided the copyright notice and this permission notice
are preserved on all copies.

@ignore
Permission is granted to process this file through TeX and print the
results, provided the printed document carries copying permission
notice identical to this one except for the removal of this paragraph
(this paragraph not being relevant to the printed manual).

@end ignore
Permission is granted to copy and distribute modified versions of this
manual under the conditions for verbatim copying, provided that the entire
resulting derived work is distributed under the terms of a permission
notice identical to this one.

Permission is granted to copy and distribute translations of this manual
into another language, under the above conditions for modified versions,
except that this permission notice may be stated in a translation approved
by Free Software Foundation, Inc.
@end ifinfo

@titlepage
@title ebrefile
@subtitle Refile a catalog file in a CD-ROM book.
@subtitle Edition @value{EDITION} for EB Library version @value{VERSION}
@subtitle @value{UPDATED}
@author by Motoyuki Kasahara

@page
@vskip 0pt plus 1filll
Copyright @copyright{} 1998, 99, 2000, 01  Motoyuki Kasahara

Permission is granted to make and distribute verbatim copies of
this manual provided the copyright notice and this permission notice
are preserved on all copies.

Permission is granted to copy and distribute modified versions of this
manual under the conditions for verbatim copying, provided that the entire
resulting derived work is distributed under the terms of a permission
notice identical to this one.

Permission is granted to copy and distribute translations of this manual
into another language, under the above conditions for modified versions,
except that this permission notice may be stated in a translation approved
by Free Software Foundation, Inc.
@end titlepage

@node Top, Introduction, (dir), (dir)
@ifinfo
This is edition @value{EDITION}, for EB Library version @value{VERSION}.
@end ifinfo

@menu
* Introduction::                Introduction.
* Invoking ebrefile::           Invoking @code{ebrefile}.
* Summary of Options::          Summary of Options to @code{ebrefile}.

 --- The Detailed Node Listing ---

Invoking @code{ebrefile}

* Select Subbooks::             Select Subbooks.
* Combination with ebzip::      Combination with @code{ebzip}.
@end menu

@c ===================================================================
@node Introduction, Invoking ebrefile, Top, Top
@chapter Introduction

A CD-ROM book usually has some @dfn{subbooks}.
For example, a certain CD-ROM book has three subbooks; Japanese
dictionary, Japense English dictinary and English Japanese dictionary.
Each subbook itself is an independent @dfn{book}.

@example
@group
            (CD-ROM book)
+-----------------------------------+
|  [English Dicctionary] (subbook)  |
|  [Japanese Dicctionary](subbook)  |
|  [Encyclopedia]        (subbook)  |
+-----------------------------------+
@end group
@end example

A CD-ROM book of EB/EBG/EBXA/EBXA-C/S-EBXA format has the file
@file{CATALOG},
and a CD-ROM book of EPWING format has the file @file{CATALOGS}.
The files define what subbooks the CD-ROM book has.
They are resides at the top directory of the CD-ROM book.

@code{ebrefile} reads an original catalog file and builds a new catalog
file which defines the subbooks only specified by an user.
In other words, @code{ebrefile} can deletes particular subbook definitions
from a catalog file.
If a CD-ROM book has three subbooks, @code{ebrefile} can imports any
one or two subbooks to the new catalog file.
The @code{ebrefile} command is useful when you want to copy only a
part of a CD-ROM book to a hard disk. 
@code{ebrefile} is a part of EB Library distribution.

@code{ebrefile} is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2, or (at your option)
any later version.

@code{ebrefile} is distributed in the hope that it will be useful,
but @emph{without any warranty}; without even the implied warranty of
merchantability or fitness for a particular purpose.  See the
GNU General Public License for more details.

In addition, you must follow the licenses of your CD-ROM books.
Though @code{ebzip} is free software, your books may not be free.
@code{ebrefile} modifies contents of a certain file in a CD-ROM book.
Please be careful.

This is edition @value{EDITION}, for EB Library version @value{VERSION}.

@c ===================================================================
@node Invoking ebrefile, Summary of Options, Introduction, Top
@chapter Invoking @code{ebrefile}

Its usual way to invoke @code{ebrefile} is as follows:

@example
% ebrefile @var{book-path}
@end example

@noindent
@var{book-path} points to the top directory of a CD-ROM book where
the file @file{CATALOG} or @file{CATALOGS} resides.
Though you cannot specify two or more book-paths, 
you can omit book-path like as follows:

@example
% ebrefile
@end example

@noindent
In this case, @code{ebrefile} assumes that the current working directory
(@file{.}) is specified.

Since @code{ebrefile} doesn't support remote access, it rejects remote
access identifer.

@example
@group
% ebrefile ebnet://localhost/cdrom
ebrefile: ebnet is not supported
@end group
@end example

@menu
* Select Subbooks::             Select Subbooks.
* Combination with ebzip::      Combination with @code{ebzip}.
@end menu

@c -------------------------------------------------------------------
@node Select Subbooks, Combination with ebzip, Invoking ebrefile, Invoking ebrefile
@section Select Subbooks

By default, @code{ebrefile} imports all subbook definitions in an original
catalog file to a new catalog file.
In short, the new catalog file is simply copied from an original.
The default behavoir is useless.
@code{ebrefile} is usually invoked with @samp{--subbook} (@samp{-S})
option.

The @samp{--subbook} option takes an argument which is a list of
directory names of subbooks to be imported, separeted by a comma
(@samp{,}).
The @code{ebinfo} command tells you what subbooks your book contains
and what their directory names are.
Suppose that the current working directory is a top directory of a
CD-ROM book.

@example
@group
% ebinfo
disc type: EB/EBG/EBXA/EBXA-C/S-EBXA
character code: JIS X 0208
the number of subbooks: 3

@end group
@group
subbook 1:
  title: New English Japanese Dictionary (4th edition)
  directory: english
  search methods: word endword keyword menu
  font sizes: 16 24 30 48
  narrow font characters: 0xa121 -- 0xa24e
  wide font characters: 0xa321 -- 0xa27e

@end group
@group
subbook 2:
  title: CD-ROM French Japanese Dictionary (3rd edition)
  directory: french
  search methods: word endword keyword menu
  font sizes: 16 24 30 48
  narrow font characters: 
  wide font characters: 0xa321 -- 0xa27e

@end group
@group
subbook 3:
  title: Pocket German Japanese Dictionary (3rd edition)
  directory: german
  search methods: menu
  font sizes: 16 24 30 48
  narrow font characters: 
  wide font characters: 0xa321 -- 0xa27e
@end group
@end example

@noindent
(@xref{Invoking ebinfo, , Invoking @code{ebinfo}, ebinfo, ebinfo},
for more details about the @code{ebinfo} command).
@*
In this example, there are three subbooks in the book, and their 
directory names are @code{english}, @code{french} and @code{german}.

Invoking the following command, @code{ebrefile} build a new catalog file
which has definitions of @code{english} and @code{french} only.

@example
% ebrefile --subbook english,french
@end example

@noindent
Case of the directory names are not sensitve.
An argument to @samp{--subbook} can be splitted like as follows:

@example
% ebrefile --subbook english --subbook french
@end example

@noindent
Since @code{ebrefile} cannot change an order of subbook definitions,
the order of arguments to @samp{--subbook} is not matter.

@code{ebrefile} generates new catalog file as @file{CATALOGS(S).new}.
To replace original catalog file by new one, type the following
commands:

@example
% mv catalogs catalogs.bak
% mv catalogs.new catalogs
@end example

@noindent
If you don't have to backup the original file, only the second command
is needed.

Now, refiling has been completed.
Invoke @code{ebinfo} again.
The subbook @code{germgan} is diappeared.

@example
@group
% ebinfo
disc type: EB/EBG/EBXA/EBXA-C/S-EBXA
character code: JIS X 0208
the number of subbooks: 2
@end group

@group
subbook 1:
  title: New English Japanese Dictionary (4th edition)
  directory: english
  search methods: word endword keyword menu
  font sizes: 16 24 30 48
  narrow font characters: 0xa121 -- 0xa24e
  wide font characters: 0xa321 -- 0xa27e

@end group
@group
subbook 2:
  title: CD-ROM French Japanese Dictionary (3rd edition)
  directory: french
  search methods: word endword keyword menu
  font sizes: 16 24 30 48
  narrow font characters: 
  wide font characters: 0xa321 -- 0xa27e
@end group
@end example

If you have already copied whole the CD-ROM book onto a hard disk,
you may remove files of the subbook @code{german}.
When the directory name consists of lower case letters, type:

@example
% rm -r german
@end example

@c -------------------------------------------------------------------
@node Combination with ebzip,  , Select Subbooks, Invoking ebrefile
@section Combination with @code{ebzip}

@code{ebrefile} can be used together with the @code{ebzip} command,
which compresses files in a CD-ROM book
(@xref{Introduction, , Introduction, ebzip, ebzip}, for more details
about the @code{ebzip} command).
Usually, the same command line arguments are given to @code{ebzip}
and @code{ebrefile}.

Suppose that a CD-ROM book is mounted on @code{/cdrom}, and this
book has three subbooks; @code{english}, @code{french} and @code{german}.
By the following operation, the subbook @code{english} and @code{french}
are compressed and put under the current working directory, and the
subbook @code{german} are deleted from a subbook list.

@example
% ebzip --subbook english,french /cdrom
% ebrefile --subbook english,french /cdrom
@end example

@noindent
If you'd like to put the compressed files onto @file{/dict} instead
of the current working directory, type the following:

@example
% ebzip --output-directory /dict --subbook english,french /cdrom
% ebrefile --output-directory /dict --subbook english,french /cdrom
@end example

@c ===================================================================
@node Summary of Options,  , Invoking ebrefile, Top
@chapter Summary of @code{ebrefile} Options

The @code{ebrefile} command supports both traditional single-letter
options and mnemonic long option names.
Long option names are indicated with @samp{--} instead of @samp{-}.
Abbreviations for option names are allowed as long as they are unique.

@table @code
@item -h
@itemx --help
Output help message to standard out, then exit.

@item -o @var{directory}
@itemx --output-directory @var{directory}
Output a new catalog file under @var{directory}.
By default, @code{ebrefile} generates a new catalog file under the
current working directory (@code{.}).
(@xref{Invoking ebrefile}, for more details).

@item -S @var{subbooks}
@itemx --subbook @var{subbooks}
Specify subbooks which @code{ebrefile} imports to a new catalog file.
@var{subbooks} must be a list of directory names of subbooks separeted
by a comma (@samp{,}).
By default, all subbooks are specified as target.
(@xref{Select Subbooks}, for more details).

@item -v
@itemx --version
Output version number to standard out, then exit.
@end table

@c ===================================================================
@contents
@bye
