\input texinfo	        @c -*-texinfo-*-
@c %** start of header
@setfilename ebstopcode.info
@settitle ebstopcode
@c %** end of header

@include version-ebstopcode.texi

@dircategory CD-ROM Book Utilities
@direntry
* ebstopcode: (ebstopcode).       Analyze text in a CD-ROM book for stop code.
@end direntry

@ifinfo
ebstopcode: Analyze text in a CD-ROM book for stop code, by Motoyuki Kasahara.

Copyright @copyright{} 2003  Motoyuki Kasahara

Permission is granted to make and distribute verbatim copies of
this manual provided the copyright notice and this permission notice
are preserved on all copies.

@ignore
Permission is granted to process this file through TeX and print the
results, provided the printed document carries copying permission
notice identical to this one except for the removal of this paragraph
(this paragraph not being relevant to the printed manual).

@end ignore
Permission is granted to copy and distribute modified versions of this
manual under the conditions for verbatim copying, provided that the entire
resulting derived work is distributed under the terms of a permission
notice identical to this one.

Permission is granted to copy and distribute translations of this manual
into another language, under the above conditions for modified versions,
except that this permission notice may be stated in a translation approved
by Free Software Foundation, Inc.
@end ifinfo

@titlepage
@title ebstopcode
@subtitle Analyze text in a CD-ROM book for stop code
@subtitle Edition @value{EDITION} for EB Library version @value{VERSION}
@subtitle @value{UPDATED}
@author by Motoyuki Kasahara

@page
@vskip 0pt plus 1filll
Copyright @copyright{} 2003  Motoyuki Kasahara

Permission is granted to make and distribute verbatim copies of
this manual provided the copyright notice and this permission notice
are preserved on all copies.

Permission is granted to copy and distribute modified versions of this
manual under the conditions for verbatim copying, provided that the entire
resulting derived work is distributed under the terms of a permission
notice identical to this one.

Permission is granted to copy and distribute translations of this manual
into another language, under the above conditions for modified versions,
except that this permission notice may be stated in a translation approved
by Free Software Foundation, Inc.
@end titlepage

@node Top, Introduction, (dir), (dir)
@ifinfo
This is edition @value{EDITION}, for EB Library version @value{VERSION}.
@end ifinfo

@menu
* Introduction::                Introduction.
* Invoke ebstopcode::           Invoke @code{ebstopcode}.
* Summary of Options::          Summary of Options to @code{ebstopcode}.
@end menu

@c ===================================================================
@node Introduction, Invoke ebstopcode, Top, Top
@chapter Introduction

When you look up a word in a CD-ROM book using EB Library application,
you might wish the application stops displaying book's text at the point
where explanation of the word ends.
Howerver, EB Library cannot ensure it, since CD-ROM book has no marker in
its text which indicates end of paragraph.

Fortunately, many CD-ROM books have a @dfn{text stop code} which could
be used for substitute for end of paragraph.
EB Library guesses text stop code automatically by default, but sometimes
takes a false code.
In that case, you have to tell EB Library a correct stop code using
@dfn{Appendix}.

The @code{ebstopcode} command is a utility to analyze text stop code
in a CD-ROM book.

This is edition @value{EDITION}, for EB Library version @value{VERSION}.

@c ===================================================================
@node Invoke ebstopcode, Summary of Options, Introduction, Top
@chapter Invoke @code{ebstopcode}

Its usual way to invoke @code{ebstopcode} is as follows:

@example
% ebstopcode @var{book-path} @var{subbook}
@end example

@noindent
@var{book-path} points to the top directory of a CD-ROM book where
the file @file{catalog} or @file{catalogs} resides.
It may be a remote access identifer (@samp{ebnet://...}).
If @var{book-path} is omitted, the current working directory is assumed.

@noindent
@var{subbook} is a directory name of the target subbook.
Use the @code{ebinfo} command to see what subbooks your CD-ROM has:

@example
@group
% ebinfo /cdrom
disc type: EB/EBG/EBXA/EBXA-C/S-EBXA
character code: JIS X 0208
the number of subbooks: 2

@end group
@group
subbook 1:
  title: New English Japanese Dictionary (4th edition)
  directory: english
  search methods: word endword keyword menu
  font sizes: 16 24 30 48
  narrow font characters: 0xa121 -- 0xa24e
  wide font characters: 0xa321 -- 0xa27e

@end group
@group
subbook 2:
  title: CD-ROM French Japanese Dictionary (3rd edition)
  directory: french
  search methods: word endword keyword menu
  font sizes: 16 24 30 48
  narrow font characters: 
  wide font characters: 0xa321 -- 0xa27e

@end group
@end example

@noindent
(@xref{Invoke ebinfo, , Invoke @code{ebinfo}, ebinfo, ebinfo},
for more details about the @code{ebinfo} command).
@*
In this example, there are two subbooks in the book, and their 
directory names are @code{english} and @code{french}.

Type the follwing to analyze text stop code of the @code{english} subbook:

@example
% ebstopcode /cdrom english
@end example

@noindent
@code{ebstopcode} outputs text and candidates for stop code of the subbook,
like this:

@example
@group
=== stop-code?: 0x1f09 0x0001 ===

=== stop-code?: 0x1f41 0x0100 ===
A

=== stop-code?: 0x1f09 0x0001 ===
n 1: the blood group whose red cells carry the A antigen.

=== stop-code?: 0x1f09 0x0001 ===
2: a metric unit of length equal to one ten billionth of a meter.

=== stop-code?: 0x1f09 0x0001 ===
3: the basic unit of electric current adopted under the System
International d'Unites.

=== stop-code?: 0x1f09 0x0001 ===

=== stop-code?: 0x1f41 0x0100 ===
(snip)
@end group
@end example

Each @samp{stop-code?:} line shows a candidate for stop code.
Specifying it as text stop code, EB Library stops displaying text at
the point.

The appropriate stop code of the @code{english} subbook is
"0x1f41 0x0100".
Test the stop code using @samp{--no-candidate} and @samp{--code}
options:

@example
% ebstopcode --no-candidate --code "0x1f41 0x0100" /cdrom english
A
n 1: the blood group whose red cells carry the A antigen.
2: a metric unit of length equal to one ten billionth of a meter.
3: the basic unit of electric current adopted under the System
International d'Unites.
@end example

@c ===================================================================
@node Summary of Options,  , Invoke ebstopcode, Top
@chapter Summary of @code{ebstopcode} Options

The @code{ebstopcode} command supports both traditional single-letter
options and mnemonic long option names.
Long option names are indicated with @samp{--} instead of @samp{-}.
Abbreviations for option names are allowed as long as they are unique.

@table @code
@item -c @var{code}
@itemx --code @var{code}
Specify @var{code} as text stop code (e.g. "0x1f09 0x0001").
@code{ebstopcode} displays text until @var{code} is appeared.

@item -h
@itemx --help
Output help message to standard out, then exit.

@item -l @var{length}
@itemx --length @var{length}
Outputs text data @var{length} bytes maximum.
If @var{length} is set to 0, @code{ebstopcode} outputs the whole text.
By default, the length is set to 2048.

@item -n
@itemx --no-candidates
Suppress stop code candidates on output.

@item -v
@itemx --version
Output version number to standard out, then exit.
@end table

@samp{--code} (@samp{-c}) and @samp{--length} (@samp{-l}) options
override each other.

@c ===================================================================
@contents
@bye
