/* Automatically generated by po2tbl.sed from @PACKAGE NAME@.pot.  */

#if HAVE_CONFIG_H
# include <config.h>
#endif

#include "libgettext.h"

const struct _msg_ent _msg_tbl[] = {
  {"", 1},
  {"try `%s --help' for more information\n", 2},
  {"%s: too many subbooks\n", 3},
  {"%s: invalid subbook name `%s...'\n", 4},
  {"%s: no such subbook `%s'\n", 5},
  {"%s: too long output directory path\n", 6},
  {"%s: too many arguments\n", 7},
  {"%s: unknown subbook name `%s'\n", 8},
  {"%s: unknown font height `%s...'\n", 9},
  {"%s: unknown font height `%s'\n", 10},
  {"%s: unknown image format name `%s...'\n", 11},
  {"%s: unknown image format name `%s'\n", 12},
  {"Usage: %s [option...] [book-directory]\n", 13},
  {"Options:\n", 14},
  {"  -d  --debug  --verbose     degug mode\n", 15},
  {"  -f HEIGHT[,HEIGHT...]  --font-height HEIGHT[,HEIGHT...]\n", 16},
  {"\
                             generate fonts with HEIGHT; 16, 24, 30 or 48\n", 17},
  {"                             (default: %s)\n", 18},
  {"  -h  --help                 display this help, then exit\n", 19},
  {"  -i FORMAT[,FORMAT...]  --image-format FORMAT[,FORMAT...]\n", 20},
  {"\
                             generate fonts as FORMAT; xbm, xpm, or gif\n", 21},
  {"  -o DIRECTORY  --output-directory DIRECTORY\n", 22},
  {"                             output fonts under DIRECTORY\n", 23},
  {"  -S SUBBOOK[,SUBBOOK...]  --subbook SUBBOOK[,SUBBOOK...]\n", 24},
  {"                             target subbook\n", 25},
  {"                             (default: all subbooks)\n", 26},
  {"  -v  --version              display version number, then exit\n", 27},
  {"\
\n\
Argument:\n", 28},
  {"  book-directory             top directory of a CD-ROM book\n", 29},
  {"\
\n\
Report bugs to %s.\n", 30},
  {"%s: failed to open the file, %s: %s\n", 31},
  {"%s: failed to write to the file, %s: %s\n", 32},
  {"%s: failed to close the file, %s: %s\n", 33},
  {"disc type: ", 34},
  {"character code: ", 35},
  {"unknown\n", 36},
  {"\
the number of subbooks: %d\n\
\n", 37},
  {"subbook %d:\n", 38},
  {"  title: %s\n", 39},
  {"  directory: %s\n", 40},
  {"  search methods: ", 41},
  {"word ", 42},
  {"endword ", 43},
  {"keyword ", 44},
  {"multi ", 45},
  {"graphic ", 46},
  {"menu ", 47},
  {"copyright ", 48},
  {"  font sizes: ", 49},
  {"  narrow font characters: ", 50},
  {"  wide font characters: ", 51},
  {"  multi search %d:\n", 52},
  {"    label %d: %s\n", 53},
  {"      candidates: ", 54},
  {"exist\n", 55},
  {"not-exist\n", 56},
  {"  -m  --multi-search         also output multi-search information\n", 57},
  {"%s: invalid compression level `%s'\n", 58},
  {"  -f  --force-overwrite      force overwrite of output files\n", 59},
  {"  -i  --information          list information of compressed files\n", 60},
  {"  -k  --keep                 keep (don't delete) original files\n", 61},
  {"  -l INTEGER  --level INTEGER\n", 62},
  {"                             compression level; 0..%d\n", 63},
  {"                             (default: %d)\n", 64},
  {"  -n  --no-overwrite         don't overwrite output files\n", 65},
  {"                             ouput files under DIRECTORY\n", 66},
  {"  -q  --quiet  --silence     suppress all warnings\n", 67},
  {"  -t  --test                 only check for input files\n", 68},
  {"  -u  --uncompress           uncompress files\n", 69},
  {"  -z  --compress             compress files\n", 70},
  {"\
\n\
Default action:\n", 71},
  {"  When invoked as `ebunzip', uncompression is the default action.\n", 72},
  {"\
  When invoked as `ebzipinfo', listing information is the default action.\n", 73},
  {"  When invoked as `ebunzip.exe', uncompression is the default action.\n", 74},
  {"\
  When invoked as `ebzipinf.exe', listing information is the default \
action.\n", 75},
  {"  Otherwise, compression is the default action.\n", 76},
  {"%s: no such file: %s\n", 77},
  {"==> compress %s <==\n", 78},
  {"output to %s\n", 79},
  {"\
the input and output files are the same, skipped.\n\
\n", 80},
  {"%s: memory exhausted\n", 81},
  {"\
already exists, skip the file\n\
\n", 82},
  {"\
\n\
the file already exists: %s\n", 83},
  {"do you wish to overwrite (y or n)? ", 84},
  {"%s: failed to unlink the file: %s\n", 85},
  {"%s: failed to write to the file: %s\n", 86},
  {"%s: failed to seek the file, %s: %s\n", 87},
  {"%s: failed to read from the file, %s: %s\n", 88},
  {"%s: unexpected EOF: %s\n", 89},
  {"%4.1f%% done (%lu / %lu bytes)\n", 90},
  {"completed (%lu / %lu bytes)\n", 91},
  {"\
%lu -> %lu bytes (%4.1f%%)\n\
\n", 92},
  {"==> uncompress %s <==\n", 93},
  {"\
%lu -> %lu bytes\n\
\n", 94},
  {"%s: CRC error: %s\n", 95},
  {"%lu bytes (not compressed)\n", 96},
  {"%lu -> %lu bytes ", 97},
  {"(empty original file, ", 98},
  {"ebzip level %d compression)\n", 99},
  {"EPWING compression)\n", 100},
  {"==> copy %s <==\n", 101},
};
int _msg_tbl_length = 101;
