/* Automatically generated by po2tbl.sed from @PACKAGE NAME@.pot.  */

#if HAVE_CONFIG_H
# include <config.h>
#endif

#include "libgettext.h"

const struct _msg_ent _msg_tbl[] = {
  {"", 1},
  {"try `%s --help' for more information\n", 2},
  {"%s: too many subbooks\n", 3},
  {"%s: invalid subbook name `%s...'\n", 4},
  {"%s: no such subbook `%s'\n", 5},
  {"%s: option `%s' is ambiguous\n", 6},
  {"%s: option `--%s' doesn't allow an argument\n", 7},
  {"%s: option `%c%s' doesn't allow an argument\n", 8},
  {"%s: option `%s' requires an argument\n", 9},
  {"%s: unrecognized option `--%s'\n", 10},
  {"%s: unrecognized option `%c%s'\n", 11},
  {"%s: illegal option -- %c\n", 12},
  {"%s: invalid option -- %c\n", 13},
  {"%s: option requires an argument -- %c\n", 14},
  {"%s: option `-W %s' is ambiguous\n", 15},
  {"%s: option `-W %s' doesn't allow an argument\n", 16},
  {"%s: too long output directory path\n", 17},
  {"%s: too many arguments\n", 18},
  {"%s: unknown subbook name `%s'\n", 19},
  {"%s: unknown font height `%s...'\n", 20},
  {"%s: unknown font height `%s'\n", 21},
  {"%s: unknown image format name `%s...'\n", 22},
  {"%s: unknown image format name `%s'\n", 23},
  {"Usage: %s [option...] [book-directory]\n", 24},
  {"Options:\n", 25},
  {"  -d  --debug  --verbose     degug mode\n", 26},
  {"  -f HEIGHT[,HEIGHT...]  --font-height HEIGHT[,HEIGHT...]\n", 27},
  {"\
                             generate fonts with HEIGHT; 16, 24, 30 or 48\n", 28},
  {"                             (default: %s)\n", 29},
  {"  -h  --help                 display this help, then exit\n", 30},
  {"  -i FORMAT[,FORMAT...]  --image-format FORMAT[,FORMAT...]\n", 31},
  {"\
                             generate fonts as FORMAT; xbm, xpm, or gif\n", 32},
  {"  -o DIRECTORY  --output-directory DIRECTORY\n", 33},
  {"                             output fonts under DIRECTORY\n", 34},
  {"  -S SUBBOOK[,SUBBOOK...]  --subbook SUBBOOK[,SUBBOOK...]\n", 35},
  {"                             target subbook\n", 36},
  {"                             (default: all subbooks)\n", 37},
  {"  -v  --version              display version number, then exit\n", 38},
  {"\
\n\
Argument:\n", 39},
  {"  book-directory             top directory of a CD-ROM book\n", 40},
  {"\
\n\
Report bugs to %s.\n", 41},
  {"%s: failed to open the file, %s: %s\n", 42},
  {"%s: failed to write to the file, %s: %s\n", 43},
  {"%s: failed to close the file, %s: %s\n", 44},
  {"disc type: ", 45},
  {"character code: ", 46},
  {"unknown\n", 47},
  {"\
the number of subbooks: %d\n\
\n", 48},
  {"subbook %d:\n", 49},
  {"  title: %s\n", 50},
  {"  directory: %s\n", 51},
  {"  search methods: ", 52},
  {"word ", 53},
  {"endword ", 54},
  {"keyword ", 55},
  {"multi ", 56},
  {"graphic ", 57},
  {"menu ", 58},
  {"copyright ", 59},
  {"  font sizes: ", 60},
  {"  narrow font characters: ", 61},
  {"  wide font characters: ", 62},
  {"  multi search %d:\n", 63},
  {"    label %d: %s\n", 64},
  {"      candidates: ", 65},
  {"exist\n", 66},
  {"not-exist\n", 67},
  {"  -m  --multi-search         also output multi-search information\n", 68},
  {"%s: invalid compression level `%s'\n", 69},
  {"  -f  --force-overwrite      force overwrite of output files\n", 70},
  {"  -i  --information          list information of compressed files\n", 71},
  {"  -k  --keep                 keep (don't delete) original files\n", 72},
  {"  -l INTEGER  --level INTEGER\n", 73},
  {"                             compression level; 0..%d\n", 74},
  {"                             (default: %d)\n", 75},
  {"  -n  --no-overwrite         don't overwrite output files\n", 76},
  {"                             ouput files under DIRECTORY\n", 77},
  {"  -q  --quiet  --silence     suppress all warnings\n", 78},
  {"  -t  --test                 only check for input files\n", 79},
  {"  -u  --uncompress           uncompress files\n", 80},
  {"  -z  --compress             compress files\n", 81},
  {"\
\n\
Default action:\n", 82},
  {"  When invoked as `ebunzip', uncompression is the default action.\n", 83},
  {"\
  When invoked as `ebzipinfo', listing information is the default action.\n", 84},
  {"  When invoked as `ebunzip.exe', uncompression is the default action.\n", 85},
  {"\
  When invoked as `ebzipinf.exe', listing information is the default \
action.\n", 86},
  {"  Otherwise, compression is the default action.\n", 87},
  {"%s: no such file: %s\n", 88},
  {"==> compress %s <==\n", 89},
  {"output to %s\n", 90},
  {"\
the input and output files are the same, skipped.\n\
\n", 91},
  {"%s: memory exhausted\n", 92},
  {"\
already exists, skip the file\n\
\n", 93},
  {"\
\n\
the file already exists: %s\n", 94},
  {"do you wish to overwrite (y or n)? ", 95},
  {"%s: failed to unlink the file: %s\n", 96},
  {"%s: failed to write to the file: %s\n", 97},
  {"%s: failed to seek the file, %s: %s\n", 98},
  {"%s: failed to read from the file, %s: %s\n", 99},
  {"%s: unexpected EOF: %s\n", 100},
  {"%4.1f%% done (%lu / %lu bytes)\n", 101},
  {"completed (%lu / %lu bytes)\n", 102},
  {"\
%lu -> %lu bytes (%4.1f%%)\n\
\n", 103},
  {"==> uncompress %s <==\n", 104},
  {"\
%lu -> %lu bytes\n\
\n", 105},
  {"%s: CRC error: %s\n", 106},
  {"%lu bytes (not compressed)\n", 107},
  {"%lu -> %lu bytes ", 108},
  {"(empty original file, ", 109},
  {"ebzip level %d compression)\n", 110},
  {"EPWING compression)\n", 111},
  {"==> copy %s <==\n", 112},
};
int _msg_tbl_length = 112;
